import "./globals.css";

import NextAuthSession from "@/app/components/ nextAuthSession";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <NextAuthSession>
        <body>{children}</body>
      </NextAuthSession>
    </html>
  );
}
